# Color
#
[[plugins]]
repo = 'tomasr/molokai'


# Utility
#
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'Townk/vim-autoclose'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'
# INFO: `:FixWhitespace` で行末スペースを全て削除

[[plugins]]
repo = 'osyo-manga/vim-anzu'
hook_add= '''
  nmap n <Plug>(anzu-n-with-echo)
  nmap N <Plug>(anzu-N-with-echo)
  nmap * <Plug>(anzu-star-with-echo)
  nmap # <Plug>(anzu-sharp-with-echo)
  nmap <Esc><Esc> <Plug>(anzu-clear-search-status)
  set statusline=%{anzu#search_status()}
'''

[[plugins]]
repo        = 'scrooloose/syntastic'
hook_source = '''
  let g:syntastic_enable_signs = 1
  let g:syntastic_auto_loc_list = 2
  let g:syntastic_python_checkers = ['flake8']
  " mypyによるチェックを行う場合は以下を有効にする
  " call add(g:syntastic_python_checkers, 'mypy')
  " let g:syntastic_python_mypy_args = '--ignore-missing-imports --follow-imports=skip'
'''

[[plugins]]
repo    = 'vim-airline/vim-airline'
depends = ['vim-fugitive', 'vim-gitgutter']

[[plugins]]
repo      = 'tpope/vim-fugitive'
on_source = ['vim-airline']

[[plugins]]
repo      = 'airblade/vim-gitgutter'
on_source = ['vim-airline']
