[[plugins]]
repo     = 'Shougo/deoplete.nvim'
on_event = 'InsertEnter'
hook_add = '''
  let g:deoplete#enable_at_startup = 1

  inoremap <expr><Tab> pumvisible() ? "\<DOWN>" : "\<Tab>"
  inoremap <expr><S-Tab> pumvisible() ? "\<UP>" : "\<S-Tab>"

  set completeopt-=preview
  set completeopt+=noinsert

  " ref.) https://github.com/zchee/deoplete-jedi/wiki/Setting-up-Python-for-Neovim

  let s:python3_path = expand('~/.pyenv/versions/neovim3/bin/python')
  if filereadable(s:python3_path)
    let g:python3_host_prog = s:python3_path
  endif
'''

[[plugins]]
repo     = 'deoplete-plugins/deoplete-jedi'
on_ft    = ['python', 'python3', 'djangohtml']
hook_add = '''
  let g:deoplete#sources#jedi#show_docstring = 0
  let g:deoplete#sources#jedi#python_path = expand('~/.pyenv/versions/neovim3/bin/python')
'''

[[plugins]]
repo        = 'Shougo/neosnippet'
on_event    = 'InsertEnter'
depends     = ['neosnippet-snippets', 'vim-snippets']
hook_source = '''
  xmap <C-n> <Plug>(neosnippet_expand_target)
  imap <C-n> <Plug>(neosnippet_expand_or_jump)
  smap <C-n> <Plug>(neosnippet_expand_or_jump)

  let g:neosnippet#snippets_directory = '~/.vim/dein/repos/github.com/honza/vim-snippets/snippets'

  if has('conceal')
    set conceallevel=2 concealcursor=niv
  endif
'''

[[plugins]]
repo      = 'Shougo/neosnippet-snippets'
on_source = ['neosnippet']

[[plugins]]
repo      = 'honza/vim-snippets'
on_source = ['neosnippet']

[[plugins]]
repo   = 'mattn/benchvimrc-vim'
on_cmd = ['BenchVimrc']

# Syntax
#
[[plugins]]
repo     = 'elzr/vim-json'
on_ft    = ['json']
hook_add = '''
  let g:vim_json_syntax_conceal = 0
'''

[[plugins]]
repo  = 'stephpy/vim-yaml'
on_ft = ['yaml']

[[plugins]]
repo  = 'hail2u/vim-css3-syntax'
on_ft = ['html', 'css', 'scss', 'sass', 'vue']

[[plugins]]
repo  = 'pangloss/vim-javascript'
on_ft = ['html', 'javascript', 'javascript.jsx', 'vue']

[[plugins]]
repo        = 'mxw/vim-jsx'
on_ft       = ['html', 'javascript', 'javascript.jsx', 'vue']
hook_source = '''
  let g:jsx_ext_required = 0
'''

[[plugins]]
repo  = 'leafgarland/typescript-vim'
on_ft = ['typescript']

[[plugins]]
repo  = 'posva/vim-vue'
on_ft = ['vue']

[[plugins]]
repo        = 'fatih/vim-go'
on_source   = ['deoplete.nvim']
on_ft       = ['go']
hook_source = '''
  let g:go_highlight_functions = 1
  let g:go_highlight_methods = 1
  let g:go_highlight_structs = 1
'''
hook_post_source = '''
  call deoplete#custom#option('omni_patterns', {
  \   'go': '[^. *\t]\.\w*',
  \})
'''

[[plugins]]
repo  = 'vim-scripts/nginx.vim'
on_ft = ['nginx']

[[plugins]]
repo  = 'itkq/fluentd-vim'
on_ft = ['fluentd']

[[plugins]]
repo  = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo     = 'hdima/python-syntax'
on_ft    = ['python', 'python3', 'djangohtml']
hook_add = '''
  let g:python_highlight_all = 1
'''

[[plugins]]
repo  = 'hynek/vim-python-pep8-indent'
on_ft = ['python', 'python3', 'djangohtml']

[[plugins]]
repo     = 'hashivim/vim-terraform'
on_ft    = ['tf']
hook_add = '''
  let g:terraform_align = 1
  let g:terraform_fmt_on_save = 1
'''

[[plugins]]
repo     = 'dart-lang/dart-vim-plugin'
on_ft    = ['dart']
hook_add = '''
  let g:dart_style_guide = 2
  let g:dart_format_on_save = 1
'''

[[plugins]]
repo     = 'thosakwe/vim-flutter'
on_ft    = ['dart']
