# Color
#
[[plugins]]
repo = 'tomasr/molokai'
hook_add = '''
  let g:molokai_original = 1
  colorscheme molokai
'''


# Utility
#
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'machakann/vim-sandwich'

[[plugins]]
repo = 'Townk/vim-autoclose'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'
# INFO: `:FixWhitespace` で行末スペースを全て削除

[[plugins]]
repo     = 'osyo-manga/vim-anzu'
hook_add = '''
  nmap n <Plug>(anzu-n-with-echo)
  nmap N <Plug>(anzu-N-with-echo)
  nmap * <Plug>(anzu-star-with-echo)
  nmap # <Plug>(anzu-sharp-with-echo)
  nmap <Esc><Esc> <Plug>(anzu-clear-search-status)
'''

[[plugins]]
repo      = 'tpope/vim-fugitive'
on_source = ['vim-airline']

[[plugins]]
repo      = 'airblade/vim-gitgutter'
on_source = ['vim-airline']

[[plugins]]
repo      = 'vim-airline/vim-airline-themes'
on_source = ['vim-airline']
hook_add  = '''
  let g:airline_theme = 'molokai'
'''

[[plugins]]
repo     = 'vim-airline/vim-airline'
depends  = ['vim-fugitive', 'vim-gitgutter']
hook_add = '''
  let g:airline_powerline_fonts = 1
  let g:airline#extensions#branch#enabled = 0
  let g:airline#extensions#hunks#enabled=0
  let g:airline#extensions#virtualenv#enabled = 0
  let g:airline#parts#ffenc#skip_expected_string='utf-8[unix]'

  call airline#parts#define_raw('linenr', '%l/%L')
  call airline#parts#define_accent('linenr', 'bold')
  let g:airline_section_z = airline#section#create(['linenr', ':%c'])
'''

[[plugins]]
repo        = 'scrooloose/nerdcommenter'
hook_source = '''
  let g:NERDDefaultAlign='left'
'''

[[plugins]]
repo     = 'w0rp/ale'
hook_add = '''
  " エラー行にjump
  nmap <silent> <C-k> <Plug>(ale_previous_wrap)
  nmap <silent> <C-j> <Plug>(ale_next_wrap)

  let g:ale_lint_on_enter = 0  " ファイルオープン時に検証しない
  let g:ale_lint_on_text_changed = 0  " 入力中は検証しない
  let g:ale_lint_on_save = 1  " 保存時に検証

  let g:ale_fix_on_save = 0  " 保存時にFixする

  let g:airline#extensions#ale#enabled = 1
  let g:ale_echo_msg_error_str = 'E'
  let g:ale_echo_msg_warning_str = 'W'
  let g:ale_echo_msg_format = '[%linter%] [%severity%] %s'  " エラーメッセージの変更

  " Python
  let g:ale_python_auto_pipenv = 1
  let g:ale_python_mypy_executable = '/usr/local/bin/mypy'
  let g:ale_python_mypy_use_global = 0
  let g:ale_python_mypy_options = '--ignore-missing-imports --follow-imports=skip'
'''
